---
title: "Über die OpenX-Initiative der Berlin University Alliance"
---

## Willkommen zum OpenX-Initiative Blog

Eines der zentralen Ziele der Berlin University Alliance ist es, Open-Science-Praktiken zu fördern und zu vertiefen. Damit baut der Exzellenverbund auf der weithin unter Berliner Forschenden geteilten Meinung auf, dass Open Science ein übergeordnetes oder höchstes Ziel sein sollte und adressiert aktuelle Entwicklungen in Wissenschaftspolitik und wissenschaftlicher Praxis. 
### Unsere Mission

Wir arbeiten daran, wissenschaftliche Praktiken inklusiver und kooperativer, transparenter und nachvollziehbarer, überprüfbarer und nachnutzbarer zu gestalten. Durch die Förderung offener Wissenschaft schaffen wir:

- **Transparenz** in Forschungsprozessen
- **Zugänglichkeit** zu wissenschaftlichen Erkenntnissen  
- **Kollaboration** zwischen Institutionen
- **Innovation** durch geteiltes Wissen

### Die Berlin University Alliance

Die OpenX-Initiative ist Teil der [Berlin University Alliance](https://www.berlin-university-alliance.de/), einem Verbund aus

- **Freie Universität Berlin**
- **Humboldt-Universität zu Berlin** 
- **Technische Universität Berlin**
- **Charité – Universitätsmedizin Berlin**

### Was Sie in diesem Blog finden

In diesem Blog dokumentieren wir:

- **Projektergebnisse**
- **Die Arbeit der Botschafter*innen für eine offene Wissenschaft**
- **Tools und Tutorials** für eine offene Wissenschaft
- **Event-Berichte** und Community-Updates

### Mitmachen

Interessiert an der OpenX-Initiative? Es gibt verschiedene Wege mitzumachen:

- **Werden Sie Botschafter*in für eine offene Wissenschaft an Ihrer Fakultät/ihrem Fachbereich** - [Mehr Informationen](https://www.berlin-university-alliance.de/commitments/research-quality/openx/os-botschafter-innen/index.html)
- **Issues erstellen** - Ideen und Feedback auf [GitHub](https://github.com/scobi2022/openX-blog.github.io/issues)
- **Unsere Community Events** besuchen
- **Open Science Projekte** starten und unterstützen

### Kontakt

- GitHub: [OpenX-Blog Repository](https://github.com/scobi2022/openX-blog.github.io)
- E-Mail: [open-science@berlin-university-alliance.de]
- Website: [https://www.berlin-university-alliance.de/commitments/research-quality/open-science/index.html]

### Lizenz

Alle Inhalte dieses Blogs – sofern nicht anders angegeben – stehen unter der [Creative Commons Attribution 4.0 International License (CC BY 4.0)](https://creativecommons.org/licenses/by/4.0/).
